Upgrade Sailor to 2.6.4
elasticio/jsonata-transform-component pull request #29
Opened 2020-02-18 09:59 UTC by ElBabbler

2020-02-18 10:08 UTC, uaArsen approved these changes

2020-02-18 12:36 UTC, ShkarupaNick requested changes

2020-02-18 12:36 UTC, ShkarupaNick commented on lib/actions/transform.js
>      return Promise.resolve();
async function returns promise by default

2020-02-18 12:36 UTC, ShkarupaNick commented on lib/actions/transform.js
>      return Promise.resolve();
```suggestion
    return;
```

2020-02-18 12:36 UTC, ShkarupaNick commented on lib/actions/transform.js
> +  return Promise.resolve(messages.newMessageWithBody(result));
```suggestion
  return messages.newMessageWithBody(result);
```

2020-02-26 10:26 UTC, ShkarupaNick approved these changes

2026-08-05 13:44 UTC, closed without merging